// <auto-generated />
using Ecommerce.Catalog.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ecommerce.Catalog.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260620102323_RenameImageUrlToImageKey")]
    partial class RenameImageUrlToImageKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ecommerce.Catalog.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories", "catalog");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Electronic devices and gadgets",
                            IsActive = true,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Apparel and fashion items",
                            IsActive = true,
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Home decor and garden supplies",
                            IsActive = true,
                            Name = "Home & Garden"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Sports equipment and outdoor gear",
                            IsActive = true,
                            Name = "Sports & Outdoors"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Books, e-books, and audiobooks",
                            IsActive = true,
                            Name = "Books"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Health, beauty, and personal care products",
                            IsActive = true,
                            Name = "Health & Beauty"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Toys, games, and entertainment",
                            IsActive = true,
                            Name = "Toys & Games"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Food, drinks, and grocery items",
                            IsActive = true,
                            Name = "Food & Beverages"
                        });
                });

            modelBuilder.Entity("Ecommerce.Catalog.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ImageKey")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("Products", "catalog");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Over-ear noise-cancelling wireless headphones.",
                            IsActive = true,
                            Name = "Wireless Headphones",
                            Sku = "ELEC-WH-001",
                            StockQuantity = 0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Waterproof 4K action camera with image stabilization.",
                            IsActive = false,
                            Name = "4K Action Camera",
                            Sku = "ELEC-AC-002",
                            StockQuantity = 0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "Unisex classic-fit denim jacket.",
                            IsActive = true,
                            Name = "Classic Denim Jacket",
                            Sku = "CLOT-DJ-003",
                            StockQuantity = 0
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "100% cotton crew-neck t-shirt.",
                            IsActive = false,
                            Name = "Cotton Crew T-Shirt",
                            Sku = "CLOT-TS-004",
                            StockQuantity = 0
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Description = "10-piece stainless steel cookware set.",
                            IsActive = true,
                            Name = "Stainless Steel Cookware Set",
                            Sku = "HOME-CW-005",
                            StockQuantity = 0
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Description = "Handmade ceramic plant pot with drainage.",
                            IsActive = false,
                            Name = "Ceramic Plant Pot",
                            Sku = "HOME-PP-006",
                            StockQuantity = 0
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            Description = "Vacuum-insulated 750ml stainless steel bottle.",
                            IsActive = true,
                            Name = "Insulated Water Bottle",
                            Sku = "SPRT-WB-007",
                            StockQuantity = 0
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Description = "Non-slip 6mm yoga mat with carrying strap.",
                            IsActive = false,
                            Name = "Yoga Mat Pro",
                            Sku = "SPRT-YM-008",
                            StockQuantity = 0
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 5,
                            Description = "A craftsman's guide to software structure and design.",
                            IsActive = true,
                            Name = "Clean Architecture",
                            Sku = "BOOK-CA-009",
                            StockQuantity = 0
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            Description = "Your journey to mastery, 20th anniversary edition.",
                            IsActive = false,
                            Name = "The Pragmatic Programmer",
                            Sku = "BOOK-PP-010",
                            StockQuantity = 0
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 6,
                            Description = "Brightening facial serum with hyaluronic acid.",
                            IsActive = true,
                            Name = "Vitamin C Serum",
                            Sku = "HLTH-VC-011",
                            StockQuantity = 0
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 6,
                            Description = "Rechargeable sonic toothbrush with timer.",
                            IsActive = false,
                            Name = "Electric Toothbrush",
                            Sku = "HLTH-ET-012",
                            StockQuantity = 0
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 7,
                            Description = "500-piece creative building blocks set.",
                            IsActive = true,
                            Name = "Building Blocks Set",
                            Sku = "TOYS-BB-013",
                            StockQuantity = 0
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 7,
                            Description = "Award-winning strategy board game for 2-4 players.",
                            IsActive = false,
                            Name = "Strategy Board Game",
                            Sku = "TOYS-BG-014",
                            StockQuantity = 0
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 8,
                            Description = "Single-origin medium-roast whole coffee beans, 1kg.",
                            IsActive = true,
                            Name = "Gourmet Coffee Beans",
                            Sku = "FOOD-CB-015",
                            StockQuantity = 0
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 8,
                            Description = "Loose-leaf organic green tea, 200g.",
                            IsActive = false,
                            Name = "Organic Green Tea",
                            Sku = "FOOD-GT-016",
                            StockQuantity = 0
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 5,
                            Description = "Personalized handwritten letter on premium paper.",
                            IsActive = true,
                            Name = "Letter",
                            Sku = "BOOK-LT-017",
                            StockQuantity = 50
                        });
                });

            modelBuilder.Entity("Ecommerce.Catalog.Domain.Entities.Product", b =>
                {
                    b.HasOne("Ecommerce.Catalog.Domain.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Ecommerce.Catalog.Domain.ValueObjects.Money", "Price", b1 =>
                        {
                            b1.Property<int>("ProductId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Price");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("Currency");

                            b1.HasKey("ProductId");

                            b1.ToTable("Products", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");

                            b1.HasData(
                                new
                                {
                                    ProductId = 1,
                                    Amount = 149.99m,
                                    Currency = "USD"
                                },
                                new
                                {
                                    ProductId = 2,
                                    Amount = 299.00m,
                                    Currency = "USD"
                                },
                                new
                                {
                                    ProductId = 3,
                                    Amount = 79.90m,
                                    Currency = "USD"
                                },
                                new
                                {
                                    ProductId = 4,
                                    Amount = 19.99m,
                                    Currency = "USD"
                                },
                                new
                                {
                                    ProductId = 5,
                                    Amount = 189.99m,
                                    Currency = "USD"
                                },
                                new
                                {
                                    ProductId = 6,
                                    Amount = 24.50m,
                                    Currency = "USD"
                                },
                                new
                                {
                                    ProductId = 7,
                                    Amount = 29.99m,
                                    Currency = "USD"
                                },
                                new
                                {
                                    ProductId = 8,
                                    Amount = 45.00m,
                                    Currency = "USD"
                                },
                                new
                                {
                                    ProductId = 9,
                                    Amount = 39.99m,
                                    Currency = "USD"
                                },
                                new
                                {
                                    ProductId = 10,
                                    Amount = 42.50m,
                                    Currency = "USD"
                                },
                                new
                                {
                                    ProductId = 11,
                                    Amount = 27.99m,
                                    Currency = "USD"
                                },
                                new
                                {
                                    ProductId = 12,
                                    Amount = 59.99m,
                                    Currency = "USD"
                                },
                                new
                                {
                                    ProductId = 13,
                                    Amount = 34.99m,
                                    Currency = "USD"
                                },
                                new
                                {
                                    ProductId = 14,
                                    Amount = 49.99m,
                                    Currency = "USD"
                                },
                                new
                                {
                                    ProductId = 15,
                                    Amount = 18.99m,
                                    Currency = "USD"
                                },
                                new
                                {
                                    ProductId = 16,
                                    Amount = 12.99m,
                                    Currency = "USD"
                                },
                                new
                                {
                                    ProductId = 17,
                                    Amount = 5.00m,
                                    Currency = "USD"
                                });
                        });

                    b.Navigation("Price")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
