// <auto-generated />
using Ecommerce.Catalog.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ecommerce.Catalog.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260416131724_RemoveUniqueIndexOnCategoryName")]
    partial class RemoveUniqueIndexOnCategoryName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ecommerce.Catalog.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories", "catalog");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Electronic devices and gadgets",
                            IsActive = true,
                            Name = "Electronics",
                            Slug = "electronics"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Apparel and fashion items",
                            IsActive = true,
                            Name = "Clothing",
                            Slug = "clothing"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Home decor and garden supplies",
                            IsActive = true,
                            Name = "Home & Garden",
                            Slug = "home-garden"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Sports equipment and outdoor gear",
                            IsActive = true,
                            Name = "Sports & Outdoors",
                            Slug = "sports-outdoors"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Books, e-books, and audiobooks",
                            IsActive = true,
                            Name = "Books",
                            Slug = "books"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Health, beauty, and personal care products",
                            IsActive = true,
                            Name = "Health & Beauty",
                            Slug = "health-beauty"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Toys, games, and entertainment",
                            IsActive = true,
                            Name = "Toys & Games",
                            Slug = "toys-games"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Food, drinks, and grocery items",
                            IsActive = true,
                            Name = "Food & Beverages",
                            Slug = "food-beverages"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
