services:
  ecommerce-api:
    container_name: ecommerce-api
    image: ecommerce
    build:
      context: .
      dockerfile: Ecommerce.AppHost/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ConnectionStrings__CatalogDb=${CATALOG_DB_CONNECTION_STRING}
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      ecommerce-db:
        condition: service_healthy

  ecommerce-db:
    container_name: ecommerce-db
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ecommerce-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  ecommerce-db-data:
