services:
  ecommerce-api:
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Cors__AllowedOrigins__0=https://localhost:8082
    volumes:
      - ${USERPROFILE}/.aspnet/https:/https:ro

  ecommerce-web:
    volumes:
      - ${USERPROFILE}/.aspnet/https:/https:ro

  ecommerce-db:
    env_file:
      - .env
    ports:
      - "1433:1433"
