services:
  ecommerce-api:
    container_name: ecommerce-api
    image: ecommerce
    build:
      context: .
      dockerfile: Ecommerce.AppHost/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ConnectionStrings__EcommerceDb
    depends_on:
      ecommerce-db:
        condition: service_healthy
    networks:
      - ecommerce-net

  ecommerce-db:
    container_name: ecommerce-db
    image: postgres:17
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - ecommerce-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ecommerce-net

volumes:
  ecommerce-db-data:

networks:
  ecommerce-net:
    driver: bridge
